mysql.config:
   localhostconn:
      host:localhost
      port:3306
      db:spider
      user:root
      password:*******
      charset:utf8
   222conn:
      host:192.168.1.222
      port:3306
      db:jep
      user:root
      password:************
      charset:utf8
   43conn:
      host:172.22.69.43
      port:3306
      db:spider
      user:spider
      password:*********
      charset:utf8
   41conn:
     host:172.22.69.41
     port:3306
     db:spider_123
     user:root
     password:*******
     charset:utf8
   41conn_test:
     host:172.22.69.41
     port:3306
     db:spider_test
     user:root
     password:*********
     charset:utf8
   67.25conn:
     host:172.22.67.25
     port:3306
     db:spider
     user:root
     password:****
     charset:utf8
   1.103conn:
     host:192.168.1.103
     port:3306
     db:spider
     user:spider
     password:************
     charset:utf8
   myconn_test:
     host:123.57.40.151
     port:3306
     db:spider_test
     user:root
     password:***********
     charset:utf8


mongodb.config:
   localhostconn:
      host:localhost
      port:27017
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp
   180conn:
      host:192.168.1.180
      port:27017
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp
   69conn:
      host:172.22.69.35
      port:20000
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp
   69.41conn:
      host:172.22.69.41
      port:20000
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp
   67.25conn:
      host:172.22.67.25
      port:20000
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp
   73-81-102conn:
      host:192.168.1.73|192.168.1.81|192.168.1.102
      port:27017
      datadb:spider_data
      fixeddb:spider_url_fixed
      tempdb:spider_url_temp

redis.config.common:
   localhostconn:
      host:localhost
      port:6379
      db:0

   41conn:
     host:172.22.69.41
     port:6379
     db:0

redis.config.wechat:
   localhostconn:
      host:localhost
      port:6379
      db:0

   41conn:
     host:172.22.69.41
     port:6379
     db:0
redis.config.colony:
   colony:
      host:172.22.69.35|172.22.69.36|172.22.69.37|172.22.69.38|172.22.69.40|172.22.69.45
      port:6379
      db:0
   105-62-93colony:
      host:192.168.1.105|192.168.1.62|192.168.1.93
      port:6379
      db:0